//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Distribuicao_Atendimento
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OBZEEntities : DbContext
    {
        public OBZEEntities()
            : base("name=OBZEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_atendente> tb_atendente { get; set; }
        public virtual DbSet<tb_atendimento> tb_atendimento { get; set; }
        public virtual DbSet<tb_prioridade> tb_prioridade { get; set; }
        public virtual DbSet<tb_status_atendente> tb_status_atendente { get; set; }
        public virtual DbSet<tb_status_atendimento> tb_status_atendimento { get; set; }
    }
}
