//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Distribuicao_Atendimento
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_status_atendente
    {
        public int id_status { get; set; }
        public string descricao { get; set; }
        public Nullable<int> situacao { get; set; }
    }
}
